{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pipelines
spec:
  replicas: 1
  strategy:
    type: Recreate
  {{ if .Values.enableAntiAffinity }}
  affinity:
    # ensure pipelines won't be on the same node as elasticsearch
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - elasticsearch
        topologyKey: "kubernetes.io/hostname"
  {{ end }}
  template:
    metadata:
      labels:
        app: pipelines
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: pipelines
        image: {{ .Values.image | default "uumpa/hasadna-migdar-data-pipelines:latest" | quote }}
        args: ['server']
        ports:
        - containerPort: 5000
        resources: {{ .Values.resources }}
        env:
        - name: DPP_REDIS_HOST
          value: 127.0.0.1
        - name: DATAFLOWS_DB_ENGINE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbSecretName | quote }}
              key: DATAFLOWS_DB_ENGINE
        - name: DPP_ELASTICSEARCH
          value: elasticsearch:9200
        - name: MIGDAR_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.migdarSecretName | quote }}
              key: MIGDAR_USERNAME
        - name: MIGDAR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.migdarSecretName | quote }}
              key: MIGDAR_PASSWORD
        volumeMounts:
        - mountPath: /pipelines/data
          name: data
          subPath: data
        - mountPath: /var/redis
          name: data
          subPath: redis
      - name: nginx
        image: nginx:alpine
        command:
        - sh
        - "-c"
        - |
          echo "HELLO WORLD!" &&\
          ls -la /pipelines/data &&\
          chmod -R 777 /pipelines/data &&\
          echo "NGINX STARTING" &&\
          nginx -g "daemon off;"
        ports:
        - containerPort: 80
        resources: {"requests": {"cpu": "30m", "memory": "150Mi"}, "limits": {"memory": "300Mi"}}
        volumeMounts:
        - name: pipelines-nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - mountPath: /pipelines/data
          name: data
          subPath: data
      volumes:
      - name: data
      {{ if .Values.gcePersistentDiskName }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-{{ .Values.gcePersistentDiskName }}-gcepd
      {{ else }}
        {{ .Values.global.persistentDataVolume.type }}: {
          {{ if eq .Values.global.persistentDataVolume.type "hostPath" }}
          "path": "{{ .Values.global.persistentDataVolume.basePath }}/pipelines",
          "type": "DirectoryOrCreate"
          {{ end }}
        }
      {{ end }}
      - name: pipelines-nginx-conf
        configMap:
          name: pipelines-nginx-conf
{{ end }}
